# Generated by Django 5.2.2 on 2025-06-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0004_comment_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
    ]
