# Generated by Django 5.2.2 on 2025-06-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articles",
            options={"verbose_name": "Article", "verbose_name_plural": "Articles"},
        ),
    ]
