# Generated by Django 5.2.2 on 2025-06-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="dark_mode",
            field=models.BooleanField(default=True),
        ),
    ]
