# Generated by Django 5.2.2 on 2025-06-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_watch_notify_on_badge_watch_notify_on_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="doors",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="engine",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="car",
            name="manufacturer_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="car",
            name="plant_country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="car",
            name="safety_rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="seats",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="transmission",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="car",
            name="vehicle_type",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
