# Generated by Django 5.2.2 on 2025-06-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_comment_mentioned_users_forumpost_mentioned_users_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="comment_images/"),
        ),
    ]
